#!/usr/bin/env python3
"""Generate src/sprites.h: bitmaps for the 512x252 high-res mode.

Geometry: the terminal draws graphics at the text dot pitch, and the 9-inch
CRT gives dots a 3:5 horizontal-to-vertical pitch (p2000c-emulator,
docs/hardware.md). A 40x24-dot cell is square on the tube; 30x18 is round.

All sprites are row-major, MSB = leftmost dot, and are OR-ed (or XOR-ed for
the cursor) onto the framebuffer, so columns overlapping grid lines stay zero.
Coordinate labels reuse the terminal's own 8x12 character-ROM glyphs from the
font sheet in the sibling p2000c-emulator checkout, so they match the text plane.
"""
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
FONT_SHEET = ROOT.parent / "p2000c-emulator/assets/font/P2000C font mini.png"
LABELS = "ABCDEFGH12345678"


def ellipse_rows(width, height, outer, inner=None):
    cx, cy = (width - 1) / 2, (height - 1) / 2

    def inside(x, y, axes):
        return ((x - cx) / axes[0]) ** 2 + ((y - cy) / axes[1]) ** 2 <= 1.0

    rows = []
    for y in range(height):
        bits = 0
        for x in range(width):
            on = inside(x, y, outer) and not (inner and inside(x, y, inner))
            bits = (bits << 1) | int(on)
        rows.append(bits.to_bytes(width // 8, "big"))
    return rows


def glyph(sheet, code):
    """8x12 glyph: sheet cell (code & 15, code >> 4), 12-px pitch, green = dot."""
    rows = []
    for gy in range(12):
        bits = 0
        for gx in range(8):
            g = sheet.getpixel(((code & 0x0F) * 12 + gx, (code >> 4) * 12 + gy))[1]
            bits = (bits << 1) | int(g != 0)
        rows.append(bytes([bits]))
    return rows


def cursor_rows():
    """Corner brackets inside a cell: 40x22 dots, disjoint from the disc area."""
    rows = []
    for y in range(22):
        on = set()
        if y in (0, 21):
            on |= set(range(2, 8)) | set(range(32, 38))
        if y < 4 or y > 17:
            on |= {2, 37}
        bits = 0
        for x in range(40):
            bits = (bits << 1) | int(x in on)
        rows.append(bits.to_bytes(5, "big"))
    return rows


def c_array(name, rows, comment):
    flat = b"".join(rows)
    body = ", ".join(f"0x{b:02X}" for b in flat)
    return f"/* {comment} */\nstatic const unsigned char {name}[{len(flat)}] = {{ {body} }};\n"


if __name__ == "__main__":
    sheet = Image.open(FONT_SHEET).convert("RGB")
    parts = ["/* Generated by tools/gen_sprites.py -- do not edit. */",
             "#ifndef SPRITES_H", "#define SPRITES_H", "",
             c_array("sprite_white", ellipse_rows(40, 18, (15.0, 9.0)), "white disc: 5 bytes x 18 rows"),
             c_array("sprite_black", ellipse_rows(40, 18, (15.0, 9.0), (12.0, 7.0)), "black disc (ring): 5 bytes x 18 rows"),
             c_array("icon_white", ellipse_rows(16, 10, (7.5, 4.8)), "score icon: 2 bytes x 10 rows"),
             c_array("icon_black", ellipse_rows(16, 10, (7.5, 4.8), (5.0, 2.8)), "score icon (ring): 2 bytes x 10 rows"),
             c_array("sprite_cursor", cursor_rows(), "cell cursor brackets: 5 bytes x 22 rows"),
             c_array("sprite_hint", [b"\x7e"] * 3, "legal-move mark: 1 byte x 3 rows"),
             "/* character-ROM glyphs A-H, 1-8: 1 byte x 12 rows each */",
             f"static const unsigned char glyphs[{len(LABELS)}][12] = {{"]
    for c in LABELS:
        parts.append("    { " + ", ".join(f"0x{r[0]:02X}" for r in glyph(sheet, ord(c))) + f" }}, /* {c} */")
    parts += ["};", "", "#endif"]
    (ROOT / "src/sprites.h").write_text("\n".join(parts) + "\n")
    print("wrote src/sprites.h")
